### ISSUE TITLE
Error 500 when two requests are made in very quick succession

### ISSUE THREAD

**Issue by jacobalbano** [Kaliumhexacyanoferrat/GenHTTP#493]
When I make several HTTP requests in quick succession immediately after startup, sometimes the request will fail with error 500. Retrying the request will succeed.

**Example**

```csharp

record class Model();

class TestResource
{
    [ResourceMethod] public Model Get() => new();
}

// ...

var layout = Layout.Create();
layout.AddService("test", new TestResource());
```

```javascript

function test() {
    fetch('/test')
        .then(x => x.json())
        .then(x => console.log(x));
}

// need to make multiple calls without awaiting
test();
test();
```

> System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary\`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at GenHTTP.Api.Protocol.FlexibleContentType.Get(String rawType, String charset)
   at GenHTTP.Api.Protocol.FlexibleContentType.Parse(String header)
   at GenHTTP.Modules.Conversion.Providers.SerializationRegistry.GetSerialization(IRequest request)
   at GenHTTP.Modules.Reflection.ResponseProvider.GetResponseAsync(IRequest request, IHandler handler, Object result, Action\`1 adjustments)
   at GenHTTP.Modules.Reflection.MethodHandler.HandleAsync(IRequest request)
   at GenHTTP.Modules.Layouting.Provider.LayoutRouter.HandleAsync(IRequest request)
   at GenHTTP.Modules.Layouting.Provider.LayoutRouter.HandleAsync(IRequest request)
   at GenHTTP.Modules.ErrorHandling.Provider.ErrorSentry`1.HandleAsync(IRequest request)

**Additional Information**

- The error is caused by the non-concurrent cache update in [this function](https://github.com/Kaliumhexacyanoferrat/GenHTTP/blob/53dda749ed9d44efe2638c89d049c215fd9ad021/API/Protocol/ContentType.cs#L456)
- Once the cache is populated, this error will no longer fail for the same content type. 
- Present in both version 8.3.0 and 8.4.0

**Comment by Kaliumhexacyanoferrat** [comment]
@jacobalbano : Fixed in 8.4.1 available via nuget, thanks for the detailled report again.
